name: "godot-ci export"

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]

env:
  GODOT_VERSION: 4.6
  EXPORT_NAME: test-project
  TEMPLATE_PATH: /github/home/.local/share/godot/export_templates
  PROJECT_PATH: .

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    environment: github-pages
    container:
      image: barichello/godot-ci:4.6
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -vp ${TEMPLATE_PATH}
          ls /root/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ${TEMPLATE_PATH}/${GODOT_VERSION}.stable
      - name: Web Build and Deploy
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          mkdir -vp _site
          godot --headless --export-release "Web" _site/index.html
          apt-get -y update && apt-get -y install curl unzip zip
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
          ./butler login
          zip -r site _site
          ./butler push site.zip playdonttell/doom3:web-final
